version: '3'

services:


  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    image: jinghongbo/beimi:mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: beimi
    volumes:
      - mysql_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  serve:
    build:
      context: .
      dockerfile: docker/serve/Dockerfile
    image: jinghongbo/beimi:serve

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    image: jinghongbo/beimi:web

    ports:
      # 游戏界面的访问端口号
      - 80:80
volumes:
  mysql_data: