version: '3'

services:
  mysql:
    #build:
      #context: .
      #dockerfile: docker/mysql/Dockerfile
    #image: jinghongbo/beimi:mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: beimi
    volumes:
      - ./docker/mysql/conf:/etc/mysql/conf.d
    #  - ./docker/mysql/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  serve:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    image: jinghongbo/beimi:serve

    ports:
      # 后台管理地址的端口号
      - 8080:8080
      # socket端口号
      - 9081:9081
  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    image: jinghongbo/beimi:client

    ports:
      # 游戏界面的访问端口号
      - 8081:80
