version: '3'
services:
  mysql:
    image: jinghongbo/beimi:mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: beimi
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  serve:
    image: jinghongbo/beimi:serve
  client:
    image: jinghongbo/beimi:client
  proxy:
    image: jinghongbo/beimi:proxy
    ports:
      - 8000:80
volumes:
  mysql_data: